//
//  HomeVM.swift
//  Netflix
//
//  Created by ********* on 31/05/2020.
//

import Foundation


class HomeVM: ObservableObject {
    @Published var movies = [Category:[Movie]]()
    init() {
        setupMovies()
    }
    func setupMovies() {
        movies[.trending] = [Movie(name: "DARK",
                                   thumbnailURL: URL(string: "https://picsum.photos/200/300")!,
                                   types: [.comedy,.crime,.dystopian],
                                   year: 2020,
                                   rating: "TV-MA",
                                   numberOfSeasons: 4,
                                   episodes: episodes,
                                   promoText:"Watch Season 4 Now",
                                   defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                          description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                          season: 2,
                                                                          episode: 1),
                                   cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                   creators:"Baran bo Odan, Jantje Friese",
                                   moreLike: [Movie(name: "TRAVELERS",
                                                    thumbnailURL: URL(string: "https://picsum.photos/200/301")!,
                                                    types: [.comedy,.crime,.dystopian],
                                                    year: 2020, rating: "TV-MA",
                                                    numberOfSeasons: 10,
                                                    episodes: episodes,
                                                    promoText:"Watch Season 4 Now",
                                                    defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                                           description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                                           season: 2,
                                                                                           episode: 1),
                                                    cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                                    creators:"Baran bo Odan, Jantje Friese"),
                                              Movie(name: "COMMUNITY",
                                                    thumbnailURL: URL(string: "https://picsum.photos/200/302")!,
                                                    types: [.comedy,.crime,.dystopian],
                                                    year: 2020,
                                                    rating: "TV-MA",
                                                    numberOfSeasons: 3,
                                                    episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),
                                                    cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                                    creators:"Baran bo Odan, Jantje Friese",
                                                    moreLike: movielikeThis,trailers:trailersData)]),
                             Movie(name: "TRAVELERS", thumbnailURL: URL(string: "https://picsum.photos/200/301")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 10, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                   moreLike: movielikeThis,trailers:trailersData),
                             Movie(name: "COMMUNITY", thumbnailURL: URL(string: "https://picsum.photos/200/302")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 3, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                   moreLike: movielikeThis,trailers:trailersData),
                             Movie(name: "ALONE", thumbnailURL: URL(string: "https://picsum.photos/200/303")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 1, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                   moreLike: movielikeThis,trailers:trailersData),
                             Movie(name: "HANNIBAL", thumbnailURL: URL(string: "https://picsum.photos/200/304")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                   moreLike: movielikeThis,trailers:trailersData),
                             Movie(name: "AFTERLIFE", thumbnailURL: URL(string: "https://picsum.photos/200/305")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 1, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                   moreLike: movielikeThis,trailers:trailersData)]
        movies[.newRelease] = [Movie(name: "DARK", thumbnailURL: URL(string: "https://picsum.photos/200/306")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                     moreLike: movielikeThis,trailers:trailersData),
                               Movie(name: "TRAVELERS", thumbnailURL: URL(string: "https://picsum.photos/200/307")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                     moreLike: movielikeThis,trailers:trailersData),
                               Movie(name: "COMMUNITY", thumbnailURL: URL(string: "https://picsum.photos/200/308")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 3, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                     moreLike: movielikeThis,trailers:trailersData),
                               Movie(name: "ALONE", thumbnailURL: URL(string: "https://picsum.photos/200/309")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons:5, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                     moreLike: movielikeThis,trailers:trailersData),
                               Movie(name: "HANNIBAL", thumbnailURL: URL(string: "https://picsum.photos/200/310")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons:7, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                     moreLike: movielikeThis,trailers:trailersData),
                               Movie(name: "AFTERLIFE", thumbnailURL: URL(string: "https://picsum.photos/200/311")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 8, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                     moreLike: movielikeThis,trailers:trailersData)].shuffled()
        movies[.standUp] = [Movie(name: "DARK", thumbnailURL: URL(string: "https://picsum.photos/200/312")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                  moreLike: movielikeThis,trailers:trailersData),
                            Movie(name: "TRAVELERS", thumbnailURL: URL(string: "https://picsum.photos/200/313")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 33, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                  moreLike: movielikeThis,trailers:trailersData),
                            Movie(name: "COMMUNITY", thumbnailURL: URL(string: "https://picsum.photos/200/314")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 2, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                  moreLike: movielikeThis,trailers:trailersData),
                            Movie(name: "ALONE", thumbnailURL: URL(string: "https://picsum.photos/200/315")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 23, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                  moreLike: movielikeThis,trailers:trailersData),
                            Movie(name: "HANNIBAL", thumbnailURL: URL(string: "https://picsum.photos/200/316")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 5, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                  moreLike: movielikeThis,trailers:trailersData),
                            Movie(name: "AFTERLIFE", thumbnailURL: URL(string: "https://picsum.photos/200/317")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                  moreLike: movielikeThis,trailers:trailersData)].shuffled()
        movies[.international] = [Movie(name: "DARK", thumbnailURL: URL(string: "https://picsum.photos/200/312")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                        moreLike: movielikeThis,trailers:trailersData),
                                  Movie(name: "TRAVELERS", thumbnailURL: URL(string: "https://picsum.photos/200/313")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                        moreLike: movielikeThis,trailers:trailersData),
                                  Movie(name: "COMMUNITY", thumbnailURL: URL(string: "https://picsum.photos/200/314")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                        moreLike: movielikeThis,trailers:trailersData),
                                  Movie(name: "ALONE", thumbnailURL: URL(string: "https://picsum.photos/200/315")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                        moreLike: movielikeThis,trailers:trailersData),
                                  Movie(name: "HANNIBAL", thumbnailURL: URL(string: "https://picsum.photos/200/316")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                        moreLike: movielikeThis,trailers:trailersData),
                                  Movie(name: "AFTERLIFE", thumbnailURL: URL(string: "https://picsum.photos/200/317")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                        moreLike: movielikeThis,trailers:trailersData)].shuffled()
        movies[.watchItAgain] = [Movie(name: "DARK", thumbnailURL: URL(string: "https://picsum.photos/200/312")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                       moreLike: movielikeThis,trailers:trailersData),
                                 Movie(name: "TRAVELERS", thumbnailURL: URL(string: "https://picsum.photos/200/313")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                       moreLike: movielikeThis,trailers:trailersData),
                                 Movie(name: "COMMUNITY", thumbnailURL: URL(string: "https://picsum.photos/200/314")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                       moreLike: movielikeThis,trailers:trailersData),
                                 Movie(name: "ALONE", thumbnailURL: URL(string: "https://picsum.photos/200/315")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                       moreLike: movielikeThis,trailers:trailersData),
                                 Movie(name: "HANNIBAL", thumbnailURL: URL(string: "https://picsum.photos/200/316")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                       moreLike: movielikeThis,trailers:trailersData),
                                 Movie(name: "AFTERLIFE", thumbnailURL: URL(string: "https://picsum.photos/200/317")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                                       moreLike: movielikeThis,trailers:trailersData)].shuffled()
    }
}
let movielikeThis = [Movie(name: "DARK",
                      thumbnailURL: URL(string: "https://picsum.photos/200/300")!,
                      types: [.comedy,.crime,.dystopian],
                      year: 2020,
                      rating: "TV-MA",
                      numberOfSeasons: 4,
                      episodes: episodes,
                      promoText:"Watch Season 4 Now",
                      defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                             description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                             season: 2,
                                                             episode: 1),
                      cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                      creators:"Baran bo Odan, Jantje Friese",
                      moreLike: [Movie(name: "TRAVELERS",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/301")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020, rating: "TV-MA",
                                       numberOfSeasons: 10,
                                       episodes: episodes,
                                       promoText:"Watch Season 4 Now",
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese"),
                                 Movie(name: "COMMUNITY",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/302")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020,
                                       rating: "TV-MA",
                                       numberOfSeasons: 3,
                                       episodes: episodes,
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese")]),
                Movie(name: "TRAVELERS", thumbnailURL: URL(string: "https://picsum.photos/200/301")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 10, episodes: episodes,promoText:"Watch Season 4 Now", defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                      moreLike: [Movie(name: "TRAVELERS",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/301")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020, rating: "TV-MA",
                                       numberOfSeasons: 10,
                                       episodes: episodes,
                                       promoText:"Watch Season 4 Now",
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese"),
                                 Movie(name: "COMMUNITY",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/302")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020,
                                       rating: "TV-MA",
                                       numberOfSeasons: 3,
                                       episodes: episodes,
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese")]),
                Movie(name: "COMMUNITY", thumbnailURL: URL(string: "https://picsum.photos/200/302")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 3, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                      moreLike: [Movie(name: "TRAVELERS",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/301")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020, rating: "TV-MA",
                                       numberOfSeasons: 10,
                                       episodes: episodes,
                                       promoText:"Watch Season 4 Now",
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese"),
                                 Movie(name: "COMMUNITY",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/302")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020,
                                       rating: "TV-MA",
                                       numberOfSeasons: 3,
                                       episodes: episodes,
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese")]),
                Movie(name: "ALONE", thumbnailURL: URL(string: "https://picsum.photos/200/303")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 1, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                      moreLike: [Movie(name: "TRAVELERS",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/301")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020, rating: "TV-MA",
                                       numberOfSeasons: 10,
                                       episodes: episodes,
                                       promoText:"Watch Season 4 Now",
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese"),
                                 Movie(name: "COMMUNITY",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/302")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020,
                                       rating: "TV-MA",
                                       numberOfSeasons: 3,
                                       episodes: episodes,
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese")]),
                Movie(name: "HANNIBAL", thumbnailURL: URL(string: "https://picsum.photos/200/304")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 4, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                      moreLike: [Movie(name: "TRAVELERS",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/301")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020, rating: "TV-MA",
                                       numberOfSeasons: 10,
                                       episodes: episodes,
                                       promoText:"Watch Season 4 Now",
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese"),
                                 Movie(name: "COMMUNITY",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/302")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020,
                                       rating: "TV-MA",
                                       numberOfSeasons: 3,
                                       episodes: episodes,
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese")]),
                Movie(name: "AFTERLIFE", thumbnailURL: URL(string: "https://picsum.photos/200/305")!, types: [.comedy,.crime,.dystopian],year: 2020, rating: "TV-MA",numberOfSeasons: 1, episodes: episodes, defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending", description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.", season: 2, episode: 1),cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",creators:"Baran bo Odan, Jantje Friese",
                      moreLike: [Movie(name: "TRAVELERS",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/301")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020, rating: "TV-MA",
                                       numberOfSeasons: 10,
                                       episodes: episodes,
                                       promoText:"Watch Season 4 Now",
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese"),
                                 Movie(name: "COMMUNITY",
                                       thumbnailURL: URL(string: "https://picsum.photos/200/302")!,
                                       types: [.comedy,.crime,.dystopian],
                                       year: 2020,
                                       rating: "TV-MA",
                                       numberOfSeasons: 3,
                                       episodes: episodes,
                                       defaultEpisodeInfo: CurrentEpisodeInfo(episodeName: "Begining and Ending",
                                                                              description: "Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum Lorem Ipsum.",
                                                                              season: 2,
                                                                              episode: 1),
                                       cast:"Louis Hofmann, Oliver Masucci, Jordis Triebel",
                                       creators:"Baran bo Odan, Jantje Friese")])]


let exampleVideoURL = URL(string: "https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4")!

